'use client';

import { useRef, useState, useEffect, type MouseEvent } from 'react';
import confetti from 'canvas-confetti';
import { Download, Share2, RotateCcw, Copy, Check, Heart, ExternalLink } from 'lucide-react';
import { AuraCardData } from '../types';
import { RARITY_REGISTRY } from '../data/catalog';
import { useReducedMotion } from '../hooks/use-reduced-motion';

interface AuraCardViewProps {
  data: AuraCardData;
  onReset: () => void;
  onReRoll: () => void;
}

export default function AuraCardView({ data, onReset, onReRoll }: AuraCardViewProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  const [isHovered, setIsHovered] = useState(false);

  const config = RARITY_REGISTRY[data.tier];
  const reducedMotion = useReducedMotion();

  useEffect(() => {
    const timer = setTimeout(() => setRevealed(true), 50);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    const shareUrl = `${window.location.origin}?u=${encodeURIComponent(data.username)}`;
    document.title = `${data.username}'s Aura: ${data.title.name} — Threads Aura Card`;

    const setMeta = (property: string, content: string) => {
      const el = document.querySelector(`meta[property="${property}"]`) || document.createElement('meta');
      el.setAttribute('property', property);
      el.setAttribute('content', content);
      if (!el.parentNode) document.head.appendChild(el);
    };

    setMeta('og:title', `${data.username}'s Aura: ${data.title.name}`);
    setMeta('og:description', `${data.title.description} — ${data.tier} tier. Generated by Threads Aura Card.`);
    setMeta('og:url', shareUrl);
    setMeta('twitter:title', `${data.username}'s Aura: ${data.title.name}`);
    setMeta('twitter:description', `${data.title.description} — ${data.tier} tier.`);

    return () => {
      document.title = 'Threads Aura Card — What\'s your internet aura?';
    };
  }, [data]);

  useEffect(() => {
    if (config.confetti && !reducedMotion) {
      const duration = config.intensity === 'ultra' ? 3.5 * 1000 : 2 * 1000;
      const animationEnd = Date.now() + duration;
      const defaults = { startVelocity: 25, spread: 360, ticks: 50, zIndex: 100 };

      const randomInRange = (min: number, max: number) => Math.random() * (max - min) + min;

      const interval: NodeJS.Timeout = setInterval(() => {
        const timeLeft = animationEnd - Date.now();

        if (timeLeft <= 0) {
          return clearInterval(interval);
        }

        const particleCount = 40 * (timeLeft / duration);
        const colors =
          config.tier === 'Legendary' ? ['#f59e0b', '#fb923c', '#ea580c', '#fef3c7'] :
          config.tier === 'Mythic' ? ['#ec4899', '#8b5cf6', '#3b82f6', '#f472b6'] :
          ['#6366f1', '#3b82f6', '#1d4ed8'];

        confetti({
          ...defaults,
          particleCount,
          origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 },
          colors,
        });
        confetti({
          ...defaults,
          particleCount,
          origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 },
          colors,
        });
      }, 250);

      return () => clearInterval(interval);
    }
  }, [data.tier, config.confetti, config.intensity]);

  const handleMouseMove = (e: MouseEvent<HTMLDivElement>) => {
    if (!cardRef.current) return;
    const rect = cardRef.current.getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;
    const mouseX = e.clientX - rect.left - width / 2;
    const mouseY = e.clientY - rect.top - height / 2;
    const rX = (mouseY / (height / 2)) * -6;
    const rY = (mouseX / (width / 2)) * 6;
    setTilt({ x: rX, y: rY });
  };

  const handleMouseLeave = () => {
    setIsHovered(false);
    setTilt({ x: 0, y: 0 });
  };

  const handleDownload = async () => {
    if (!cardRef.current || downloading) return;
    setDownloading(true);

    const tierHex: Record<string, string> = {
      Common: '#94a3b8', Uncommon: '#34d399', Rare: '#60a5fa',
      Epic: '#a855f7', Legendary: '#fbbf24', Mythic: '#f472b6', Secret: '#ffffff'
    };
    const tierGrad: Record<string, string[]> = {
      Common: ['#1e293b','#0f172a'], Uncommon: ['#064e3b','#0f172a'],
      Rare: ['#1e3a5f','#0f172a'], Epic: ['#3b0764','#0f172a'],
      Legendary: ['#451a03','#0f172a'], Mythic: ['#4c0519','#0f172a'],
      Secret: ['#0a0a0a','#050505']
    };
    const tc = tierHex[data.tier] || '#94a3b8';
    const bg = tierGrad[data.tier] || ['#0f172a','#050505'];

    try {
      const cvs = document.createElement('canvas');
      cvs.width = 1350;
      cvs.height = 900;
      const ctx = cvs.getContext('2d');
      if (!ctx) { setDownloading(false); return; }

      const grad = ctx.createRadialGradient(300, 200, 50, 675, 450, 800);
      grad.addColorStop(0, bg[0]);
      grad.addColorStop(1, bg[1]);
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, 1350, 900);

      const dot = ctx.createRadialGradient(100, 100, 10, 100, 100, 400);
      dot.addColorStop(0, tc + '25');
      dot.addColorStop(1, 'transparent');
      ctx.fillStyle = dot;
      ctx.fillRect(0, 0, 1350, 900);

      ctx.textAlign = 'left';

      const displayName = data.profile?.displayName || data.username;

      ctx.fillStyle = '#94a3b8';
      ctx.font = '18px monospace';
      ctx.fillText('THREADS AURA CARD', 50, 50);

      ctx.fillStyle = tc;
      ctx.font = 'bold 16px monospace';
      ctx.fillText(data.tier.toUpperCase(), 50, 78);

      ctx.fillStyle = '#f1f5f9';
      ctx.font = 'bold 44px sans-serif';
      ctx.fillText(data.title.name, 50, 165);

      ctx.fillStyle = '#94a3b8';
      ctx.font = '18px sans-serif';
      ctx.fillText(data.title.description, 50, 200);

      ctx.fillStyle = tc + '99';
      ctx.font = 'italic 16px sans-serif';
      ctx.fillText(config.description, 50, 230);

      ctx.fillStyle = '#e2e8f0';
      ctx.font = 'bold 26px sans-serif';
      ctx.fillText(displayName, 50, 295);

      ctx.fillStyle = '#64748b';
      ctx.font = '18px monospace';
      ctx.fillText(data.username, 50, 325);

      if (data.profile?.bio) {
        ctx.fillStyle = '#94a3b8';
        ctx.font = '16px sans-serif';
        const bioText = data.profile.bio.length > 180 ? data.profile.bio.slice(0, 180) + '...' : data.profile.bio;
        ctx.fillText(bioText, 50, 355);
      }

      const metricsX = 530;
      data.metrics.slice(0, 8).forEach((m, i) => {
        const col = i < 4 ? 0 : 1;
        const row = i < 4 ? i : i - 4;
        const x = metricsX + col * 390;
        const y = 60 + row * 68;

        ctx.fillStyle = '#94a3b8';
        ctx.font = '18px sans-serif';
        ctx.fillText(`${m.emoji} ${m.label}`, x, y + 16);

        ctx.fillStyle = tc;
        ctx.font = 'bold 22px sans-serif';
        ctx.textAlign = 'right';
        ctx.fillText(String(m.score), x + 330, y + 16);
        ctx.textAlign = 'left';

        ctx.fillStyle = '#ffffff15';
        ctx.fillRect(x, y + 26, 330, 16);
        ctx.fillStyle = tc;
        ctx.fillRect(x, y + 26, (m.score / 100) * 330, 16);
      });

      const badgeY = 420;
      ctx.textAlign = 'left';
      data.badges.slice(0, 4).forEach((b, i) => {
        const bx = 50 + i * 185;
        ctx.fillStyle = '#ffffff12';
        ctx.beginPath();
        (ctx as any).roundRect(bx, badgeY, 165, 38, 19);
        ctx.fill();
        ctx.fillStyle = '#cbd5e1';
        ctx.font = '16px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(`${b.emoji} ${b.name}`, bx + 82, badgeY + 26);
      });

      ctx.fillStyle = '#64748b';
      ctx.font = 'italic 18px sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText(`"${data.insight}"`, 50, 510);

      ctx.fillStyle = '#475569';
      ctx.font = '15px sans-serif';
      ctx.textAlign = 'left';
      ctx.fillText('threads-aura-card.vercel.app', 50, 840);

      ctx.fillStyle = '#475569';
      ctx.font = '15px sans-serif';
      ctx.textAlign = 'right';
      ctx.fillText('by Kuril Dev', 1300, 840);

      const image = cvs.toDataURL('image/png', 1.0);
      const link = document.createElement('a');
      link.download = `${data.username.replace('@', '')}_aura_summary.png`;
      link.href = image;
      link.click();
    } catch {}
    setDownloading(false);
  };

  const handleCopyLink = () => {
    const shareUrl = `${window.location.origin}?u=${encodeURIComponent(data.username)}`;
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShareThreads = () => {
    const caption = `My internet aura is: ${data.title.name} (${data.tier} Tier) ✨ ${data.insight} Discover yours at Threads Aura Card!`;
    const url = `https://threads.com/intent/post?text=${encodeURIComponent(caption)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const initials = data.username.replace('@', '').substring(0, 2).toUpperCase();
  const displayName = data.profile?.displayName || data.username;
  const avatarUrl = data.profile?.avatarUrl || null;
  const bio = data.profile?.bio || null;
  const [avatarError, setAvatarError] = useState(false);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen px-4 py-12 md:py-16 text-slate-100 font-sans">

      <div
        className="fixed inset-0 pointer-events-none transition-all duration-1000 ease-out z-0 opacity-20 filter blur-[150px]"
        style={{
          background: `radial-gradient(circle at 50% 50%, ${config.glowColor.replace('0.15', '0.6').replace('0.18', '0.6').replace('0.3', '0.6').replace('0.45', '0.6').replace('0.6', '0.8')}, transparent 60%)`
        }}
      />

      <div className="w-full max-w-md z-10 text-center mb-6">
        <h2 className="text-xl font-display font-medium text-slate-400 mb-1">Your Vibe has Crystalized</h2>
        <p className="text-sm text-slate-500">Press download to save or post directly to your Threads feed.</p>
      </div>

      <div
        id="aura-card-capture"
        ref={cardRef}
        onMouseMove={handleMouseMove}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={handleMouseLeave}
        className={`w-full max-w-[420px] aspect-[4/5] rounded-3xl p-5 relative select-none cursor-pointer z-10 bg-[#050505] overflow-hidden ${revealed ? 'animate-card-reveal shine-effect' : 'opacity-0 scale-[0.85]'}`}
        style={{
          transform: revealed && isHovered ? `perspective(1000px) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg) scale(1.02)` : revealed ? 'perspective(1000px) rotateX(0deg) rotateY(0deg) scale(1)' : 'none',
          boxShadow: isHovered ? `0 0 80px -15px ${config.glowColor}, inset 0 0 0 1px rgba(255,255,255,0.08)` : `0 0 60px -20px rgba(168, 85, 247, 0.3), inset 0 0 0 1px rgba(255,255,255,0.05)`
        }}
      >
        <div className="absolute top-0 left-0 right-0 h-[2px] rounded-t-3xl z-20" style={{ background: `linear-gradient(90deg, ${config.textColor.includes('emerald') ? '#34d399, #10b981' : config.textColor.includes('blue') ? '#60a5fa, #3b82f6' : config.textColor.includes('purple') ? '#a855f7, #9333ea' : config.textColor.includes('amber') ? '#fbbf24, #f59e0b' : config.textColor.includes('pink') ? '#f472b6, #ec4899' : '#e2e8f0, #94a3b8'})` }} />

        <div className={`absolute inset-0 bg-gradient-to-br ${config.gradient} opacity-25 z-0`} />

        <div className="absolute inset-0 bg-[radial-gradient(#ffffff02_1px,transparent_1px)] [background-size:14px_14px] pointer-events-none opacity-30 z-0" />

        <div className={`absolute inset-0 rounded-3xl border pointer-events-none z-10 transition-all duration-500 ${
          data.tier === 'Common' ? 'border-white/10' :
          data.tier === 'Uncommon' ? 'border-emerald-600/30' :
          data.tier === 'Rare' ? 'border-blue-600/40' :
          data.tier === 'Secret' ? 'border-white/10' :
          'border-white/5'
        }`} />

        <div id="aura-card-main-body" className="h-full flex flex-col relative z-10 p-2">

          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <span className="text-[9px] tracking-[0.15em] font-mono font-medium text-slate-500 uppercase">AURA CARD</span>
              <span className={`text-[9px] font-mono font-bold tracking-wider px-2 py-0.5 rounded uppercase border bg-black/60 ${config.borderColor} ${config.textColor}`}>
                {data.tier}
              </span>
            </div>
            <span className="text-[9px] font-mono text-slate-600">{data.generatedAt}</span>
          </div>

          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-xl flex-shrink-0 overflow-hidden border border-white/10 bg-white/5">
              {avatarUrl && !avatarError ? (
                <img
                  src={avatarUrl}
                  alt={displayName}
                  className="w-full h-full object-cover"
                  onError={() => setAvatarError(true)}
                />
              ) : (
                <div className="w-full h-full flex items-center justify-center">
                  <span className="text-xs font-bold text-slate-400">{initials}</span>
                </div>
              )}
            </div>
            <div className="flex flex-col text-left min-w-0">
              <span className="text-sm font-semibold text-slate-200 truncate">{displayName}</span>
              <span className="text-[9px] text-slate-500 font-mono truncate">{data.username}</span>
              {bio && <span className="text-[8px] text-slate-400 leading-tight mt-0.5 line-clamp-2">{bio}</span>}
            </div>
          </div>

          <div className="mb-3 text-left">
            <div className="text-xl font-bold tracking-tight mb-0.5 text-white leading-tight">
              {data.title.name}
            </div>
            <p className="text-[10px] text-slate-400 leading-relaxed">{data.title.description}</p>
            <p className={`text-[8px] italic mt-0.5 ${config.textColor}`}>{config.description}</p>
          </div>

          <div className="flex-1 min-h-0">
            <div className="space-y-1">
              {data.metrics.slice(0, 10).map((metric) => (
                <div key={metric.id}>
                  <div className="flex items-center justify-between mb-0.5">
                    <span className="text-[9px] text-slate-400 truncate">{metric.emoji} {metric.label}</span>
                    <span className={`font-mono text-[9px] font-bold flex-shrink-0 ml-2 ${config.textColor}`}>{metric.score}</span>
                  </div>
                  <div className="h-1 bg-white/10 rounded-full overflow-hidden">
                    <div className="h-full rounded-full transition-all duration-1000" style={{
                      width: `${metric.score}%`,
                      background: `linear-gradient(90deg, ${config.textColor.includes('emerald') ? '#10b981' : config.textColor.includes('blue') ? '#3b82f6' : config.textColor.includes('purple') ? '#9333ea' : config.textColor.includes('amber') ? '#f59e0b' : config.textColor.includes('pink') ? '#ec4899' : '#8b5cf6'}, ${config.textColor.includes('emerald') ? '#34d399' : config.textColor.includes('blue') ? '#60a5fa' : config.textColor.includes('purple') ? '#a855f7' : config.textColor.includes('amber') ? '#fbbf24' : config.textColor.includes('pink') ? '#f472b6' : '#a855f7'})`
                    }} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="flex flex-wrap gap-1 mt-3 mb-2">
            {data.badges.slice(0, 3).map((badge) => (
              <div
                key={badge.name}
                className="flex items-center gap-1 text-[8px] font-medium px-2 py-0.5 rounded-full bg-white/5 border border-white/10 text-slate-300"
                title={badge.description}
              >
                <span>{badge.emoji}</span>
                <span>{badge.name}</span>
              </div>
            ))}
          </div>

          <div className="pt-2 border-t border-white/5 text-left">
            <p className="text-[9px] italic text-slate-500 leading-relaxed line-clamp-2">
              &ldquo;{data.insight}&rdquo;
            </p>
          </div>

          <div className="mt-2 flex items-center justify-between text-[7px] font-mono text-slate-600 uppercase tracking-wider">
            <span>Threads Aura Card</span>
            <span>by Kuril Dev</span>
          </div>

        </div>
      </div>

      <div className="w-full max-w-md z-10 text-center mt-3">
        <p className="text-[10px] text-slate-500 font-sans leading-relaxed">
          Cuma buat seru-seruan ya, bukan tes psikologi beneran ✨
        </p>
      </div>

      <div className="w-full max-w-[390px] mt-6 space-y-3 z-10">
        <button
          onClick={handleDownload}
          disabled={downloading}
          className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-slate-100 to-slate-200 hover:from-white hover:to-white text-slate-950 font-sans font-semibold py-3 px-4 rounded-xl transition-all shadow-lg active:scale-[0.98] cursor-pointer disabled:opacity-50"
        >
          <Download className="w-4 h-4" />
          {downloading ? 'Rendering...' : 'Download Aura Summary (Landscape)'}
        </button>

        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={handleShareThreads}
            className="flex items-center justify-center gap-2 bg-slate-900 hover:bg-slate-850 text-slate-200 font-sans font-medium py-3 px-4 rounded-xl border border-slate-800 transition-all active:scale-[0.98] cursor-pointer"
          >
            <Share2 className="w-4 h-4 text-slate-400" />
            Post to Threads
          </button>

          <button
            onClick={handleCopyLink}
            className="flex items-center justify-center gap-2 bg-slate-900 hover:bg-slate-850 text-slate-200 font-sans font-medium py-3 px-4 rounded-xl border border-slate-800 transition-all active:scale-[0.98] cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4 text-slate-400" />}
            {copied ? 'Copied Vibe!' : 'Copy Link'}
          </button>
        </div>

        <div className="flex items-center justify-between pt-4 border-t border-slate-900 text-xs">
          <button
            onClick={onReRoll}
            className="flex items-center gap-1.5 text-slate-400 hover:text-slate-200 transition-colors py-1 cursor-pointer"
            title="Keep the username, but shuffle the seed to try and roll a rarer tier!"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            Re-roll Aura Tier
          </button>

          <button
            onClick={onReset}
            className="text-slate-500 hover:text-slate-300 transition-colors py-1 font-medium cursor-pointer"
          >
            Analyze another profile →
          </button>
        </div>
      </div>

      <footer className="mt-12 text-center text-xs text-slate-600 font-sans space-y-1.5">
        <p className="flex items-center justify-center gap-1">
          <span>Built with</span>
          <Heart className="w-3 h-3 text-red-500 fill-red-500" />
          <span>by</span>
          <a
            href="https://kuril.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="font-semibold text-slate-400 hover:text-slate-200 transition-colors underline decoration-slate-700 underline-offset-2"
          >
            Kuril Dev
          </a>
        </p>
        <p className="text-[11px] text-slate-600">
          Follow creator on Threads:{' '}
          <a
            href="https://threads.com/@heyitskuril"
            target="_blank"
            rel="noopener noreferrer"
            className="text-slate-500 hover:text-slate-300 font-medium inline-flex items-center gap-0.5"
          >
            @heyitskuril <ExternalLink className="w-2.5 h-2.5" />
          </a>
        </p>
        <p className="text-[10px] text-slate-600 leading-relaxed max-w-md mx-auto">
          Cuma buat seru-seruan ya, bukan tes psikologi beneran ✨ Datanya diambil dari profil publik Threads kamu — jadi kadang bisa meleset atau lagi susah diakses kalau lagi rame banget.
        </p>
      </footer>

    </div>
  );
}
