'use client';

import { useRef, useState, useEffect, type MouseEvent } from 'react';
import confetti from 'canvas-confetti';
import { Download, Share2, RotateCcw, Copy, Check, Heart, ExternalLink } from 'lucide-react';
import { AuraCardData } from '../types';
import { RARITY_REGISTRY } from '../data/catalog';
import { useReducedMotion } from '../hooks/use-reduced-motion';

interface AuraCardViewProps {
  data: AuraCardData;
  onReset: () => void;
  onReRoll: () => void;
}

export default function AuraCardView({ data, onReset, onReRoll }: AuraCardViewProps) {
  const cardRef = useRef<HTMLDivElement>(null);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  const [isHovered, setIsHovered] = useState(false);

  const config = RARITY_REGISTRY[data.tier];
  const reducedMotion = useReducedMotion();

  useEffect(() => {
    const timer = setTimeout(() => setRevealed(true), 50);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    const shareUrl = `${window.location.origin}?u=${encodeURIComponent(data.username)}`;
    document.title = `${data.username}'s Aura: ${data.title.name} — Threads Aura Card`;

    const setMeta = (property: string, content: string) => {
      const el = document.querySelector(`meta[property="${property}"]`) || document.createElement('meta');
      el.setAttribute('property', property);
      el.setAttribute('content', content);
      if (!el.parentNode) document.head.appendChild(el);
    };

    setMeta('og:title', `${data.username}'s Aura: ${data.title.name}`);
    setMeta('og:description', `${data.title.description} — ${data.tier} tier. Generated by Threads Aura Card.`);
    setMeta('og:url', shareUrl);
    setMeta('twitter:title', `${data.username}'s Aura: ${data.title.name}`);
    setMeta('twitter:description', `${data.title.description} — ${data.tier} tier.`);

    return () => {
      document.title = 'Threads Aura Card — What\'s your internet aura?';
    };
  }, [data]);

  useEffect(() => {
    if (config.confetti && !reducedMotion) {
      const duration = config.intensity === 'ultra' ? 3.5 * 1000 : 2 * 1000;
      const animationEnd = Date.now() + duration;
      const defaults = { startVelocity: 25, spread: 360, ticks: 50, zIndex: 100 };

      const randomInRange = (min: number, max: number) => Math.random() * (max - min) + min;

      const interval: NodeJS.Timeout = setInterval(() => {
        const timeLeft = animationEnd - Date.now();

        if (timeLeft <= 0) {
          return clearInterval(interval);
        }

        const particleCount = 40 * (timeLeft / duration);
        const colors =
          config.tier === 'Legendary' ? ['#f59e0b', '#fb923c', '#ea580c', '#fef3c7'] :
          config.tier === 'Mythic' ? ['#ec4899', '#8b5cf6', '#3b82f6', '#f472b6'] :
          ['#6366f1', '#3b82f6', '#1d4ed8'];

        confetti({
          ...defaults,
          particleCount,
          origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 },
          colors,
        });
        confetti({
          ...defaults,
          particleCount,
          origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 },
          colors,
        });
      }, 250);

      return () => clearInterval(interval);
    }
  }, [data.tier, config.confetti, config.intensity]);

  const handleMouseMove = (e: MouseEvent<HTMLDivElement>) => {
    if (!cardRef.current) return;
    const rect = cardRef.current.getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;
    const mouseX = e.clientX - rect.left - width / 2;
    const mouseY = e.clientY - rect.top - height / 2;
    const rX = (mouseY / (height / 2)) * -6;
    const rY = (mouseX / (width / 2)) * 6;
    setTilt({ x: rX, y: rY });
  };

  const handleMouseLeave = () => {
    setIsHovered(false);
    setTilt({ x: 0, y: 0 });
  };

  const handleDownload = async () => {
    if (!cardRef.current || downloading) return;
    setDownloading(true);

    const card = cardRef.current;
    const originalWidth = card.style.width;
    const originalMaxWidth = card.style.maxWidth;

    try {
      card.style.width = '432px';
      card.style.maxWidth = '432px';

      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(card, {
        useCORS: true,
        allowTaint: true,
        scale: 2.5,
        backgroundColor: '#0B0B0F',
        logging: false,
        onclone: (documentClone: Document) => {
          const cloneCard = documentClone.getElementById('aura-card-main-body');
          if (cloneCard) {
            cloneCard.style.transform = 'none';
          }
        }
      });

      const image = canvas.toDataURL('image/png', 1.0);
      const link = document.createElement('a');
      link.download = `${data.username.replace('@', '')}_aura_card.png`;
      link.href = image;
      link.click();
    } catch (err) {
      console.error('Failed to export Aura Card', err);
    } finally {
      card.style.width = originalWidth;
      card.style.maxWidth = originalMaxWidth;
      setDownloading(false);
    }
  };

  const handleCopyLink = () => {
    const shareUrl = `${window.location.origin}?u=${encodeURIComponent(data.username)}`;
    navigator.clipboard.writeText(shareUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShareThreads = () => {
    const caption = `My internet aura is: ${data.title.name} (${data.tier} Tier) ✨ ${data.insight} Discover yours at Threads Aura Card!`;
    const url = `https://threads.com/intent/post?text=${encodeURIComponent(caption)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  };

  const initials = data.username.replace('@', '').substring(0, 2).toUpperCase();
  const displayName = data.profile?.displayName || data.username;
  const avatarUrl = data.profile?.avatarUrl || null;
  const bio = data.profile?.bio || null;

  return (
    <div className="flex flex-col items-center justify-center min-h-screen px-4 py-12 md:py-16 text-slate-100 font-sans">

      <div
        className="fixed inset-0 pointer-events-none transition-all duration-1000 ease-out z-0 opacity-20 filter blur-[150px]"
        style={{
          background: `radial-gradient(circle at 50% 50%, ${config.glowColor.replace('0.15', '0.6').replace('0.18', '0.6').replace('0.3', '0.6').replace('0.45', '0.6').replace('0.6', '0.8')}, transparent 60%)`
        }}
      />

      <div className="w-full max-w-md z-10 text-center mb-6">
        <h2 className="text-xl font-display font-medium text-slate-400 mb-1">Your Vibe has Crystalized</h2>
        <p className="text-sm text-slate-500">Press download to save or post directly to your Threads feed.</p>
      </div>

      <div
        id="aura-card-capture"
        ref={cardRef}
        onMouseMove={handleMouseMove}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={handleMouseLeave}
        className={`w-full max-w-[420px] aspect-[4/5] rounded-3xl p-8 relative select-none cursor-pointer z-10 bg-[#050505] overflow-hidden ${revealed ? 'animate-card-reveal shine-effect' : 'opacity-0 scale-[0.85]'}`}
        style={{
          transform: revealed && isHovered ? `perspective(1000px) rotateX(${tilt.x}deg) rotateY(${tilt.y}deg) scale(1.02)` : revealed ? 'perspective(1000px) rotateX(0deg) rotateY(0deg) scale(1)' : 'none',
          boxShadow: isHovered ? `0 0 80px -15px ${config.glowColor}, inset 0 0 0 1px rgba(255,255,255,0.08)` : `0 0 60px -20px rgba(168, 85, 247, 0.3), inset 0 0 0 1px rgba(255,255,255,0.05)`
        }}
      >
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-[#A855F7] to-[#EC4899]" style={{ background: `linear-gradient(90deg, ${config.textColor.includes('emerald') ? '#10b981, #34d399' : config.textColor.includes('blue') ? '#3b82f6, #60a5fa' : config.textColor.includes('fuchsia') ? '#d946ef, #e879f9' : config.textColor.includes('amber') ? '#f59e0b, #fbbf24' : config.textColor.includes('pink') ? '#ec4899, #f472b6' : '#a855f7, #ec4899'})` }} />

        <div className={`absolute inset-0 bg-gradient-to-br ${config.gradient} opacity-20 z-0`} />

        <div className="absolute inset-0 bg-[radial-gradient(#ffffff02_1px,transparent_1px)] [background-size:16px_16px] pointer-events-none opacity-40 z-0" />

        {data.tier === 'Epic' || data.tier === 'Legendary' ? (
          <div className="absolute -inset-[1px] rounded-3xl overflow-hidden pointer-events-none z-0">
            <div className="absolute inset-[-100%] bg-conic from-fuchsia-500 via-purple-500 to-fuchsia-500 animate-spin" style={{ animationDuration: '4s' }} />
          </div>
        ) : data.tier === 'Mythic' ? (
          <div className="absolute -inset-[1px] rounded-3xl overflow-hidden pointer-events-none z-0">
            <div className="absolute inset-[-100%] bg-conic from-pink-500 via-indigo-500 to-pink-500 animate-spin" style={{ animationDuration: '3s' }} />
            <div className="absolute inset-0 bg-black rounded-3xl holographic-shift" style={{ animation: 'holographic-shift 6s ease-in-out infinite' }} />
          </div>
        ) : null}

        <div className={`absolute inset-0 rounded-3xl border pointer-events-none z-10 transition-all duration-500 ${
          data.tier === 'Common' ? 'border-white/10' :
          data.tier === 'Uncommon' ? 'border-emerald-500/30' :
          data.tier === 'Rare' ? 'border-blue-500/40 shadow-[inset_0_0_20px_-5px_rgba(59,130,246,0.15)]' :
          data.tier === 'Secret' ? 'border-white/5' :
          'border-transparent'
        }`} />

        <div id="aura-card-main-body" className="h-full flex flex-col justify-between relative z-10">

          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-[10px] tracking-widest font-mono font-medium text-slate-400">AURA CARD //</span>
              <span className={`text-[10px] font-mono font-bold tracking-wider px-2 py-0.5 rounded uppercase border bg-black/50 ${config.borderColor} ${config.textColor}`}>
                {data.tier}
              </span>
            </div>
            <span className="text-xs font-mono text-slate-500">{data.generatedAt}</span>
          </div>

          <div className="flex items-center gap-3 mt-4">
            <div className={`w-12 h-12 rounded-xl flex items-center justify-center font-display font-bold text-sm tracking-wider border relative overflow-hidden bg-gradient-to-br ${config.gradient} ${config.borderColor}`}>
              {avatarUrl ? (
                <img src={avatarUrl} alt={displayName} className="w-full h-full object-cover absolute inset-0" />
              ) : (
                <>
                  <div className="absolute inset-0 bg-black/40" />
                  <span className={`relative z-10 ${config.textColor}`}>{initials}</span>
                </>
              )}
            </div>
            <div className="flex flex-col text-left">
              <span className="text-sm font-semibold font-sans text-slate-200">{displayName}</span>
              {bio && <span className="text-[10px] text-slate-400 font-sans leading-tight mt-0.5 line-clamp-2">{bio}</span>}
              <span className="text-[10px] text-slate-500 font-mono uppercase tracking-wider mt-0.5">Threads Presence</span>
            </div>
          </div>

          <div className="my-4 text-left">
            <div className="text-3xl sm:text-4xl font-display font-extrabold tracking-tight mb-2 uppercase leading-none bg-gradient-to-b from-white to-neutral-400 bg-clip-text text-transparent">
              {data.title.name}
            </div>
            <p className="text-xs text-slate-300 leading-relaxed font-sans">{data.title.description}</p>
          </div>

          <div className="my-1.5 text-left">
            {data.metrics.map((metric, idx) => {
              const barColor = config.tier === 'Secret' ? '#ffffff' : `linear-gradient(90deg, #8b5cf6, ${config.textColor.includes('emerald') ? '#10b981' : config.textColor.includes('blue') ? '#3b82f6' : config.textColor.includes('fuchsia') ? '#d946ef' : config.textColor.includes('amber') ? '#f59e0b' : config.textColor.includes('pink') ? '#ec4899' : '#a855f7'})`;

              if (idx < 2) {
                const radius = 28;
                const circumference = 2 * Math.PI * radius;
                const offset = circumference - (metric.score / 100) * circumference;
                return (
                  <div key={metric.id} className="inline-flex flex-col items-center w-1/2 align-top mb-2">
                    <div className="relative w-[64px] h-[64px] mx-auto">
                      <svg className="w-full h-full -rotate-90" viewBox="0 0 64 64">
                        <circle cx="32" cy="32" r={radius} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="4" />
                        <circle cx="32" cy="32" r={radius} fill="none" stroke="url(#ring-grad)" strokeWidth="4" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={offset} className="transition-all duration-1000" />
                        <defs><linearGradient id="ring-grad" x1="0%" y1="0%" x2="100%" y2="0%"><stop offset="0%" stopColor="#8b5cf6" /><stop offset="100%" stopColor="#a855f7" /></linearGradient></defs>
                      </svg>
                      <div className="absolute inset-0 flex items-center justify-center">
                        <span className={`text-lg ${config.textColor}`}>{metric.emoji}</span>
                      </div>
                    </div>
                    <div className={`text-[10px] font-mono font-bold ${config.textColor} mt-0.5`}>{metric.score}</div>
                    <div className="text-[8px] text-slate-500 font-mono uppercase tracking-wider text-center leading-tight">{metric.label}</div>
                  </div>
                );
              }

              return (
                <div key={metric.id} className="flex items-center gap-2 mb-1.5">
                  <span className="text-[10px] w-4 flex-shrink-0">{metric.emoji}</span>
                  <div className="flex-1 h-1.5 bg-white/10 rounded-full overflow-hidden">
                    <div className="h-full rounded-full transition-all duration-1000" style={{ width: `${metric.score}%`, background: barColor }} />
                  </div>
                  <span className={`font-mono text-[10px] font-bold w-6 text-right flex-shrink-0 ${config.textColor}`}>{metric.score}</span>
                  <span className="text-[8px] text-slate-500 font-mono uppercase w-16 truncate text-right flex-shrink-0 hidden sm:block">{metric.label}</span>
                </div>
              );
            })}
          </div>

          <div className="flex flex-wrap gap-1.5 my-3">
            {data.badges.map((badge, idx) => (
              <div
                key={badge.name}
                className={`flex items-center gap-1 text-[10px] font-medium font-mono px-2.5 py-1 rounded-full bg-white/5 border border-white/10 text-slate-300 transition-all hover:scale-105 ${revealed ? 'animate-badge-pop' : ''}`}
                style={{ animationDelay: `${0.6 + idx * 0.12}s` }}
                title={badge.description}
              >
                <span>{badge.emoji}</span>
                <span>{badge.name}</span>
              </div>
            ))}
          </div>

          <div className="mt-2 pt-3 border-t border-white/5 text-left">
            <p className="text-xs italic text-slate-400 font-sans leading-relaxed">
              &ldquo;{data.insight}&rdquo;
            </p>
          </div>

          <div className="mt-4 flex items-center justify-between text-[9px] font-mono text-slate-500 uppercase tracking-wider">
            <span>Created with Threads Aura Card</span>
            <span className="opacity-80">by Kuril Dev</span>
          </div>

        </div>
      </div>

      <div className="w-full max-w-md z-10 text-center mt-3">
        <p className="text-[10px] text-slate-500 font-sans leading-relaxed">
          Cuma buat seru-seruan ya, bukan tes psikologi beneran ✨
        </p>
      </div>

      <div className="w-full max-w-[390px] mt-6 space-y-3 z-10">
        <button
          onClick={handleDownload}
          disabled={downloading}
          className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-slate-100 to-slate-200 hover:from-white hover:to-white text-slate-950 font-sans font-semibold py-3 px-4 rounded-xl transition-all shadow-lg active:scale-[0.98] cursor-pointer disabled:opacity-50"
        >
          <Download className="w-4 h-4" />
          {downloading ? 'Rendering Image...' : 'Download Threads Aura Card (PNG)'}
        </button>

        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={handleShareThreads}
            className="flex items-center justify-center gap-2 bg-slate-900 hover:bg-slate-850 text-slate-200 font-sans font-medium py-3 px-4 rounded-xl border border-slate-800 transition-all active:scale-[0.98] cursor-pointer"
          >
            <Share2 className="w-4 h-4 text-slate-400" />
            Post to Threads
          </button>

          <button
            onClick={handleCopyLink}
            className="flex items-center justify-center gap-2 bg-slate-900 hover:bg-slate-850 text-slate-200 font-sans font-medium py-3 px-4 rounded-xl border border-slate-800 transition-all active:scale-[0.98] cursor-pointer"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4 text-slate-400" />}
            {copied ? 'Copied Vibe!' : 'Copy Link'}
          </button>
        </div>

        <div className="flex items-center justify-between pt-4 border-t border-slate-900 text-xs">
          <button
            onClick={onReRoll}
            className="flex items-center gap-1.5 text-slate-400 hover:text-slate-200 transition-colors py-1 cursor-pointer"
            title="Keep the username, but shuffle the seed to try and roll a rarer tier!"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            Re-roll Aura Tier
          </button>

          <button
            onClick={onReset}
            className="text-slate-500 hover:text-slate-300 transition-colors py-1 font-medium cursor-pointer"
          >
            Analyze another profile →
          </button>
        </div>
      </div>

      <footer className="mt-12 text-center text-xs text-slate-600 font-sans space-y-1.5">
        <p className="flex items-center justify-center gap-1">
          <span>Built with</span>
          <Heart className="w-3 h-3 text-red-500 fill-red-500" />
          <span>by</span>
          <a
            href="https://kuril.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="font-semibold text-slate-400 hover:text-slate-200 transition-colors underline decoration-slate-700 underline-offset-2"
          >
            Kuril Dev
          </a>
        </p>
        <p className="text-[11px] text-slate-600">
          Follow creator on Threads:{' '}
          <a
            href="https://threads.com/@heyitskuril"
            target="_blank"
            rel="noopener noreferrer"
            className="text-slate-500 hover:text-slate-300 font-medium inline-flex items-center gap-0.5"
          >
            @heyitskuril <ExternalLink className="w-2.5 h-2.5" />
          </a>
        </p>
        <p className="text-[10px] text-slate-600 leading-relaxed max-w-md mx-auto">
          Cuma buat seru-seruan ya, bukan tes psikologi beneran ✨ Datanya diambil dari profil publik Threads kamu — jadi kadang bisa meleset atau lagi susah diakses kalau lagi rame banget.
        </p>
      </footer>

    </div>
  );
}
